version: '3'

services:
  goapp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    container_name: goapp
    #entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - app-network
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
    #  - ./mysql:/var/lib/mysql
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    environment:
#      - MYSQL_DATABASE=take_home
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  # mysql_test:
  #   image: mysql:5.7
  #   command: --innodb-use-native-aio=0
  #   container_name: mysql_test
  #   restart: always
  #   tty: true
  #   volumes:
  #     - ./mysql_test:/var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=take_home_test
  #     - MYSQL_ROOT_PASSWORD=root
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge